### ISSUE TITLE
Food

### ISSUE THREAD

**Issue by Sorseg** [Sorseg/snake#1]
1. Еда появляется в рандомных координатах на экране.
2. Еда должна оставаться на своих координатах до момента, как координаты башки змеи совпадут с координатами еды.
3. Когда координаты башки змеи и еды совпадают, еда должна исчезнуть и появиться на других рандомных координатах на карте.
4. Длина змеи после "съедания" еды должна увеличиться на 1.

must be implemented in logic.py

**Comment by fonegg** [comment]
Done (653a446c0224de3afa99ac5196459062f20347bb)
